---
require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5.0

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 20

RSpec/DescribeClass:
  Exclude:
    - 'spec/bankrupt/tasks_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/bankrupt/tasks_spec.rb'

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/bankrupt/tasks_spec.rb'

RSpec/NestedGroups:
  Max: 6

RSpec/StubbedMock:
  Enabled: false
