---
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4.0

Layout/ExtraSpacing:
  AllowForAlignment: false

Metrics/BlockLength:
  Max: 80
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 15

RSpec/DescribeClass:
  Exclude:
    - 'spec/bankrupt/tasks_spec.rb'

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/bankrupt/tasks_spec.rb'

RSpec/NestedGroups:
  Max: 6
