---
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3.7

Layout/ExtraSpacing:
  AllowForAlignment: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 15

RSpec/NestedGroups:
  Max: 5
