---
sudo: false

language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

before_install:
  - gem update --system
  - gem --version

script:
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec yard

notifications:
  email: false
